### ISSUE TITLE
Variables aren't picked up when calling from frontend

### ISSUE THREAD

**Issue by autsada** [aaronwlee/Oak-GraphQL#10]
Hi

I finished making the API, it works well in the playground and now I connected this API to the frontend. The queries that don't require variables work, but the queries and mutations that require variables don't work. 

I have tested both with my next.js frontend and postman.

 Here are screenshots from using postman.
![Screenshot (25)](https://user-images.githubusercontent.com/34464087/83708584-cc13e980-a646-11ea-8893-399fa9719364.png)
![Screenshot (26)](https://user-images.githubusercontent.com/34464087/83708600-d1713400-a646-11ea-84b7-5870ec30535b.png)

**Comment by aaronwlee** [comment]
![right_solution](https://user-images.githubusercontent.com/55095886/83709735-1ec0b780-a5ed-11ea-89f7-4524e92017bf.JPG)
Here is the right solution and you can find [more information](https://graphql.org/learn/queries/#variables) here.

**Comment by aaronwlee** [comment]
Also, it might be easier to use [apollo](https://www.apollographql.com/docs/react/) for the client-side part.

**Comment by autsada** [comment]
Hi arronwlee,

Thank you for your quick reply.
Actually I used apollo on the frontend, and I have defined my query on the frontend same way as your example. Here is my code.

```
query($userId: String!) {
    me(userId: $userId) {
      id
      username
      email
      roles
      created_at
    }
  }
```

I think it is not because of the frontend,  which I also have tested the same code with my other Graphql API made in Node.js and it works fine.

I have tested your example code using a variable in the playground, it works when I enter the argument directly, but it doesn't when I put it as a variable. Please see the screenshots below.

![Screenshot (29)](https://user-images.githubusercontent.com/34464087/83715211-17ce8f00-a657-11ea-90bf-9e82238748aa.png)
![Screenshot (30)](https://user-images.githubusercontent.com/34464087/83715219-1b621600-a657-11ea-9643-f80c7e4392db.png)

**Comment by aaronwlee** [comment]
as far as mine is working fine
![result](https://user-images.githubusercontent.com/55095886/83715674-fdb39300-a5fb-11ea-8aa3-b3fe34adb618.JPG)

I think you're using the wrong version...
can you try reload the module or use the 0.2 version. `https://deno.land/x/oak_graphql@0.2/mod.ts`

**Comment by autsada** [comment]
Yes, that may cause the problem. I will test it and will update you soonest.

Thank for your help :)

**Comment by autsada** [comment]
Hi @aaronwlee 

Yes, the wrong version was indeed cause a problem. Now it works.

Thank you very much for your time.
