### ISSUE TITLE
authentication middleware for auth errors

### ISSUE THREAD

**Issue by shendkardevesh** [aaronwlee/Oak-GraphQL#12]
unable to send authentication error from context middleware or from app.use middleware,
can you suggest me the better way for handling the authentication, might be missing something to accomplish that.

**Comment by aaronwlee** [comment]
version up to 0.3, here is  some example

when global context error
```ts
const GraphQLService = await applyGraphQL({
  typeDefs: types,
  resolvers: resolvers,
  context: (ctx) => {
    if(...check cookie) {
      throw new GQLError("Authentication error")
    }
    return { user: "Aaron" };
  }
})
```

simple resolver level error handling
```ts
const resolvers = {
  Query: {
    getUser: (parent: any, { id }: any, context: any, info: any) => {
      if(context.user !== "Aaron") {
        throw new GQLError("Authentication error")
      }
      return {
        firstName: "wooseok",
        lastName: "lee",
      };
    },
  },
  Mutation: {
    setUser: (parent: any, { input: { firstName, lastName } }: any, context: any, info: any) => {
      console.log("input:", firstName, lastName);
      return {
        done: true,
      };
    },
  },
};
```

**Comment by shendkardevesh** [comment]
where do i get GQLError

**Comment by shendkardevesh** [comment]
hey can you also help me out, how can i get the query name or the info in context 
const GraphQLService = await applyGraphQL({
  typeDefs: types,
  resolvers: resolvers,
  context: (ctx) => {
    if(...check cookie) {
      throw new GQLError("Authentication error")
    }
    return { user: "Aaron" };
  }
})
so that i can only perform authentication selected api's

**Comment by aaronwlee** [comment]
you must reload the [module](https://deno.land/manual/linking_to_external_code/reloading_modules)

```
deno run --reload https://deno.land/x/oak_graphql/mod.ts
```

the query name is in the request body

```ts
const { response, request } = ctx;
const body = (await request.body()).value;
body.operationName
body.variables
body.query
```

if you want to select to apply the authentication, then I'd like to recommend checking the context inside of the resolvers level.

**Comment by shendkardevesh** [comment]
hey sorry but once reload, now its giving error on routes and allowedMethods
app.use(GraphQLService.routes(), GraphQLService.allowedMethods());

error: TS2339 [ERROR]: Property 'routes' does not exist on type 'Promise<Router<Record<string | number, string | undefined>, Record<string, any>>>'.
app.use(GraphQLService.routes(), GraphQLService.allowedMethods());

**Comment by aaronwlee** [comment]
Please update the Oak framework to latest version too

**Comment by shendkardevesh** [comment]
Thanks a lot @aaronwlee  for your quick response
