### ISSUE TITLE
Server keeps logging "contentType application/json" on running

### ISSUE THREAD

**Issue by nabameet** [aaronwlee/Oak-GraphQL#14]
Whenever I start my Oak-GraphQL API, after running, it keeps on logging `contentType application/json` at the terminal. It is very annoying. Is there any fix for that?

**Comment by aaronwlee** [comment]
that's not `oak-graphql` problem, please upgrade the oak.

**Comment by nabameet** [comment]
@aaronwlee Thanks. Upgrading oak fixed the problem.
