### ISSUE TITLE
GraphQL Error Responses are not displaying properly.

### ISSUE THREAD

**Issue by nabameet** [aaronwlee/Oak-GraphQL#15]
The Errors look like this:
`{
    "error": {
      "message": "[\n  {\n    \"message\": \"Username Doesn't Exist\",\n    \"locations\": [\n      {\n        \"line\": 2,\n        \"column\": 3\n      }\n    ],\n    \"path\": [\n      \"login\"\n    ]\n  }\n]"
    }
  }`

Although it should look something like this:
`{
    "error": [
      {
      "message": "Username Doesn't Exist",
      "locations": [
         {
           "line": 2,
           "column": 3,
         }
       ],
       "path": [
         "login"
        ]
      }
    ]
}`

It would be very helpful if there is a fix. Or tell me if I am doing something wrong.

**Comment by aaronwlee** [comment]
did you have tried this?
```
throw new GQLError({ "type": "error" })
```

**Comment by autsada** [comment]
I am facing the same problem and the `"throw new GQLError({"type": "error"}) ` does not solve this problem. 
I solve this by downgrading to version 0.2

**Comment by nabameet** [comment]
`throw new GQLError({"type": "error"})` did not help. Is there any other way than downgrading?

**Comment by aaronwlee** [comment]
can you guys try the latest version? I can't find the problems...
I've got like this
```js
{
  errors: [
    {
      message: { error: "auth error" },
      locations: [{ line: 2, column: 3 }],
      path: ["getUser"],
    },
  ],
  data: {
    getUser: null,
  },
}
```

**Comment by nabameet** [comment]
I ran `deno run --reload https://deno.land/x/oak_graphql/mod.ts` It found 53 errors. Now it's not working at all. This is the error: `Uncaught SyntaxError: The requested module 'https://cdn.pika.dev/graphql@^15.0.0' does not provide an export named 'GraphQLFieldConfig'`

**Comment by aaronwlee** [comment]
@nabameet sorry the CDN version control had some issues.

can you reload the module or use 0.4 version?

**Comment by nabameet** [comment]
@aaronwlee Thanks for the quick reply. I have reloaded it and now it is running. But the error problem is there.

`throw new GQLError("Pass")` is giving this output:

```{
  "error": {
    "message": "[\n  {\n    \"message\": \"Pass\",\n    \"locations\": [\n      {\n        \"line\": 2,\n        \"column\": 3\n      }\n    ],\n    \"path\": [\n      \"register\"\n    ]\n  }\n]"
  }
}```

Am I doing something wrong?

**Comment by nabameet** [comment]
Can you tell me how do you throw the errors?

**Comment by aaronwlee** [comment]
```ts
import { Application } from "https://deno.land/x/oak/mod.ts";
import { applyGraphQL, gql, GQLError } from "./mod.ts";

const app = new Application();

app.use(async (ctx, next) => {
  await next();
  const rt = ctx.response.headers.get("X-Response-Time");
  console.log(`${ctx.request.method} ${ctx.request.url} - ${rt}`);
});

app.use(async (ctx, next) => {
  const start = Date.now();
  await next();
  const ms = Date.now() - start;
  ctx.response.headers.set("X-Response-Time", `${ms}ms`);
});

const types = (gql as any)`
type User {
  firstName: String
  lastName: String
}

input UserInput {
  firstName: String
  lastName: String
}

type ResolveType {
  done: Boolean
}

type Query {
  getUser(id: String): User 
}

type Mutation {
  setUser(input: UserInput!): ResolveType!
}
`;

const resolvers = {
  Query: {
    getUser: (parent: any, { id }: any, context: any, info: any) => {
      console.log("id", id, context);
      if (context.user === "Aaron") {
        throw new GQLError({error: "auth error"})
      }
      return {
        firstName: "wooseok",
        lastName: "lee",
      };
    },
  },
  Mutation: {
    setUser: (parent: any, { input: { firstName, lastName } }: any, context: any, info: any) => {
      console.log("input:", firstName, lastName);
      return {
        done: true,
      };
    },
  },
};

const GraphQLService = await applyGraphQL({
  typeDefs: types,
  resolvers: resolvers,
  context: (ctx) => {
    return { user: "Aaron" };
  }
})


app.use(GraphQLService.routes(), GraphQLService.allowedMethods());

console.log("Server start at http://localhost:8080");
await app.listen({ port: 8080 });
```

**Comment by nabameet** [comment]
Didn't work for me. `throw new GQLError({ error: "Pass" })` returned the same response.

**Comment by aaronwlee** [comment]
can you give me more detail about your env?
also, there are possibilities that you're using the cached old version.
can you try again with 0.4 version for now? maybe tomorrow you can use the master branch.

**Comment by nabameet** [comment]
how do i downgrade the version?

**Comment by aaronwlee** [comment]
I've tried postman, playground and react, but these are returns like this
```js
{
    "errors": [
        {
            "message": {
                "error": "auth error"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "getUser"
            ]
        }
    ],
    "data": {
        "getUser": null
    }
}
```

**Comment by aaronwlee** [comment]
https://deno.land/x/oak_graphql@0.4/mod.ts

**Comment by nabameet** [comment]
Still not working. I'm running Windows 10 with Deno v1.1.2 , latest version of oak and oak_graphql

**Comment by aaronwlee** [comment]
where did you run the code?

**Comment by nabameet** [comment]
tried using cmd, git bash, graphql playground and postman. Didn't help. Postman is returning 
```
{
    "message": "[\n  {\n    \"message\": {\n      \"error\": \"Pass\"\n    },\n    \"locations\": [\n      {\n        \"line\": 2,\n        \"column\": 3\n      }\n    ],\n    \"path\": [\n      \"demo\"\n    ]\n  }\n]"
}
```
and Graphql Playground:
```
{
  "error": {
    "message": "[\n  {\n    \"message\": {\n      \"error\": \"Pass\"\n    },\n    \"locations\": [\n      {\n        \"line\": 2,\n        \"column\": 3\n      }\n    ],\n    \"path\": [\n      \"demo\"\n    ]\n  }\n]"
  }
}
```

**Comment by aaronwlee** [comment]
sorry I can't help...
I need to find a way to reproduce your issue. but I don't know which cases are the result of that problem. 
try to use in javascript with `JSON.parse` for temporary.

**Comment by aaronwlee** [comment]
@nabameet can you give me your code example?

**Comment by nabameet** [comment]
```
// REGISTER User
export const register = async (
  username: string,
  email: string,
  password: string,
  confirmPassword: string
) => {
  if (password.length < 8) throw new GQLError({ error: "Pass" });
  if (password !== confirmPassword) throw new GQLError("Password incorrect");
  password = await hashPassword(password);
  if (await users.findOne({ username })) throw new GQLError("Username Exists");
  if (await users.findOne({ email })) throw new GQLError("Email Exists");
  const newUserID = await users.insertOne({ username, email, password });
  const newUser = await users.findOne({ _id: newUserID });
  return getUserResponse(newUser);
};
```

**Comment by aaronwlee** [comment]
@nabameet I've enhanced some error handling, I hope it's helpful. if you don't mind, can you retry this with reloaded the master module or 0.5 version?

**Comment by autsada** [comment]
I have done some quick tests using 0.5, it seems to work.

Just have one question, I have to use Oak master branch otherwise I cannot start the Graphql server. Is there any way to use Oak_Grapqh for example version 0.5 with a specific version of Oak?

**Comment by aaronwlee** [comment]
@autsada 
done! version up to 0.5.1

**Comment by autsada** [comment]
@aaronwlee 
Thank you for your quick work. I will test it out.

**Comment by nabameet** [comment]
@aaronwlee Thanks man, I've reloaded the module and it's working! Thanks for being so quick! :)

**Comment by nabameet** [comment]
@aaronwlee Sorry to disturb you again, but whenever I'm executing the query, by pressing the play button, it is console logging `here` in the terminal. I think you used it for debugging and then didn't remove.

**Comment by aaronwlee** [comment]
@nabameet done!

**Comment by autsada** [comment]
Hi,

I found that the frontend does not receive the error message with v0.5.1 and v0.5.2. So I have to downgrade to v0.2 again.

Here is the graphQLError I received on the frontend when using v0.5.1 or v0.5.2
![image](https://user-images.githubusercontent.com/34464087/86468721-38772b00-bd62-11ea-9dd8-c89571935abb.png)

Here is what I received using v0.2
![image](https://user-images.githubusercontent.com/34464087/86468829-6d837d80-bd62-11ea-8ead-17d943f36b97.png)

By the way, on the frontend I use apollo client 3

**Comment by nabameet** [comment]
I'm having the problem too. I tested with Vanilla JS using fetch.

**Comment by aaronwlee** [comment]
@autsada @nabameet Sorry for the inconvenience, I accidentally renamed the object keys. It's been fixed in the latest version.
Thank you.

**Comment by autsada** [comment]
@aaronwlee 
Thank you, is the latest version is 0.5.2?

**Comment by aaronwlee** [comment]
that's 0.5.3. I'd recommend using the master branch.
simply use without "@" and make sure to reload the module.

**Comment by autsada** [comment]
Ok, noted with many thanks.

**Comment by nabameet** [comment]
@aaronwlee awesome man. thanks

**Comment by nabameet** [comment]
This bug is fixed, so closing the issue.
