### ISSUE TITLE
Server cannot be reached

### ISSUE THREAD

**Issue by autsada** [aaronwlee/Oak-GraphQL#2]
Hi,

I have tried by copying your example code and run on my machine. I got this error in the playground.

`{
  "error": "Unexpected end of JSON input"
}`

Is there any suggestion?

Thank you

**Comment by aaronwlee** [comment]
is your playground endpoint indicates the same as your URL http://localhost:8080/graphql?

if your endpoint in a browser is http://localhost:8080/graphql, then playground URL endpoint must be same as http://localhost:8080/graphql

**Comment by autsada** [comment]
Thanks for your quick reply.

The URL in my browser is http://localhost:8080/graphql. And do I have to explicitly specify the endpoint in the code as well? I just copied the example code and didn't change anything, and I thought the "/graphql" would be a default endpoint.

**Comment by aaronwlee** [comment]
yeah... I think it's a bug that I can't fix for now. I've tried for a while 

please take a look this
https://github.com/aaronwlee/Oak-GraphQL/blob/master/mustsame.JPG
sorry for inconvenience

**Comment by autsada** [comment]
That is ok, thank you.
