### ISSUE TITLE
 Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Abdubek** [aaronwlee/Oak-GraphQL#20]
I get this error when starting the application (and when  deno run --reload https://deno.land/x/oak_graphql/mod.ts)

    error: Uncaught ReferenceError: exports is not defined
    Object.defineProperty(exports, "__esModule", {
                      ^
    at https://cdn.pika.dev/-/graphql@v14.7.0-LNtF6ErZCSf0EZG1C4Ps/dist=es2019,mode=exports/language/parser.js:3:23

I copied the application code from the documentation and did not make any changes

deno 1.2.0
v8 8.5.216
typescript 3.9.2

**Comment by Timeraa** [comment]
Can confirm

**Comment by m-barrera** [comment]
Same Problem

**Comment by aaronwlee** [comment]
Same problem...
graphql-tag is using graphql@v14.7.0, and this particular version has something wrong with loading by pika cdn.

So I have embedded gql-tag project locally then solve the problem. so painful XD
