### ISSUE TITLE
error: Uncaught Error: Another accept task is ongoing

### ISSUE THREAD

**Issue by beforesecond** [aaronwlee/Oak-GraphQL#3]
Hi,
I got error when deno run.
```
error: Uncaught Error: Another accept task is ongoing
```
My source code at https://github.com/beforesecond/deno_graphql_poc

Is there any suggestion?

Thank you.

**Comment by aaronwlee** [comment]
sorry it's a bug.
after reload the module, you can use like this.
```ts
const GraphQLService = await applyGraphQL({
  typeDefs: [user],
  resolvers: [UserResolvers],
})
```

**Comment by beforesecond** [comment]
> sorry it's a bug.
> after reloading the module, you can use it like this.
> `add an await`
> 
> ```ts
> const GraphQLService = await applyGraphQL({
>   typeDefs: [user],
>   resolvers: [UserResolvers],
> })
> ```

I tried reloading the module, and add an await but I got the same error.
```
error: Uncaught Error: Another accept task is ongoing
```
😥

**Comment by aaronwlee** [comment]
can I get to know Which env(os) are you using? it seems to not reload properly

**Comment by beforesecond** [comment]
> I cloned your project and it's working fine.
> can I get to know Which env(os) are you using? it seems to not reload properly
I used run deno reload
```
deno run --reload https://deno.land/x/oak_graphql/mod.ts
deno run --reload https://deno.land/x/oak/mod.ts
```
I encountered an error. I don't know where it is.
```
error: Uncaught Error: Another accept task is ongoing
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async ListenerImpl.accept ($deno$/net.ts:61:17)
    at async Server.acceptConnAndIterateHttpRequests (https://deno.land/std@0.53.0/http/server.ts:221:14)
    at async MuxAsyncIterator.callIteratorNext (https://deno.land/std@0.53.0/async/mux_async_iterator.ts:28:29)
```

**Comment by aaronwlee** [comment]
hum, I tried `deno run --reload https://deno.land/x/oak_graphql/mod.ts` it's not working too. I presume deno repo server also cached it...

let's try import `https://deno.land/x/oak_graphql@0.1/mod.ts`
this way will be working perfectly.

**Comment by beforesecond** [comment]
> hum, I tried `deno run --reload https://deno.land/x/oak_graphql/mod.ts` it's not working too. I presume deno repo server also cached it...
> 
> let's try import `https://deno.land/x/oak_graphql@0.1/mod.ts`
> this way will be working perfectly.

Perfect!!!
That worked for me ,Thank you.
