### ISSUE TITLE
Getting errors with deno 1.5.2

### ISSUE THREAD

**Issue by dadtmt** [aaronwlee/oak-graphql#39]
I have these errors using deno 1.5.2

```
 error: TS2464 [ERROR]: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
   public [$$asyncIterator]() {
          ~~~~~~~~~~~~~~~~~
     at https://deno.land/x/oak_graphql@0.6.2/graphql-subscriptions/pubsub-async-iterator.ts:71:10
 
 TS2464 [ERROR]: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
       [$$asyncIterator]() {
       ~~~~~~~~~~~~~~~~~
     at https://deno.land/x/oak_graphql@0.6.2/graphql-subscriptions/with-filter.ts:41:7
```

I am using docker and I have everything working using deno 1.4.6

**Comment by pamply** [comment]
Facing the same problem with:

```
deno 1.5.3 (ab7b8ba, release, x86_64-apple-darwin)
v8 8.7.220.3
typescript 4.0.5
```

**Comment by hherraz** [comment]
The same problem here!

**Comment by gtrombitas** [comment]
I have the same problem with deno version 1.5.3. For workaround approach: Does anybody know what is the latest deno version with oak-graphql works well without these error message?

**Comment by dadtmt** [comment]
@gtrombitas I have it working with this docker image: hayd/alpine-deno:1.4.6

**Comment by gtrombitas** [comment]
Thanks a lot @dadtmt! With version 1.4.6 from Deno works without errors. It is a good temporary solution until this issue will be fixed.

**Comment by dadtmt** [comment]
@gtrombitas Is this still working for you, with my full project code it is not working anymore (same errors)

**Comment by gtrombitas** [comment]
@dadtmt Yes it works but this issue sounds really interesting for me... Today I have upgraded Deno to version 1.5.4 and my project works with oak_graphql@0.6.2 but I don't know why.
After every version change from Deno I reload the cache with the following command:
`deno cache --reload --no-check file.ts`
Unfortunately I don't know how to use with Docker but maybe you should give it a try.
