### ISSUE TITLE
Do you support graphql subscriptions?

### ISSUE THREAD

**Issue by bpernick** [aaronwlee/Oak-GraphQL#7]

**Comment by aaronwlee** [comment]
now we have one :)

**Comment by bpernick** [comment]
Sure thing!

**Comment by bpernick** [comment]
Getting the following error: https://deno.land/x/oak_graphql/mod has no exported member 'PubSub'

**Comment by aaronwlee** [comment]
due to the cache, It might better to use the https://deno.land/x/oak_graphql@0.2/mod.ts
also do not forget to add the ts at the last. :)

**Comment by bpernick** [comment]
Thanks! That link fixed the download problem

**Comment by bpernick** [comment]
Now I am running your simple example with this command "deno run --allow-net --allow-read testGraphql.ts", running this query from the playground:
 query {
  getUser(id: "best") {
    firstName
    lastName
  }
}
and getting this error message: "message": "Unknown operation named \"\"."

**Comment by bpernick** [comment]
The request payload for those queries is this {"operationName":null,"variables":{},"query":"{\n  getUser(id: \"best\") {\n    firstName\n    lastName\n  }\n}\n"} -- should operation name be null? In a minute here I'll try hitting it from postman and setting the operation name

**Comment by bpernick** [comment]
The issue with the query was a non - issue... Looks like graphql is checking to make sure my queries are named.

**Comment by bpernick** [comment]
So the issue with the query was a non - issue... Looks like graphql is checking to make sure my queries are named. I went ahead and deleted that question. Sorry abt that :)

**Comment by bpernick** [comment]
It looks like Apollo's pubsub does not actually open a websocket connection, they expect you to do that separately. I'm assuming it's the same in this implementation? Right now I'm getting a complaint "Could not connect to websocket endpoint ws://localhost:8000/graphql", so I'm working on creating a websocket endpoint and connecting it to graphql.

**Comment by aaronwlee** [comment]
I presume I need to implement the WebSocket service for oak. I postpone this process due to I don't have that much time. Sorry for the inconvenience and thanks for the testing.

**Comment by bpernick** [comment]
No problem and thank you for your time as well!
