### ISSUE TITLE
Error Message: "Unknown operation named \"\"." when executing example query

### ISSUE THREAD

**Issue by nicolaszu** [aaronwlee/Oak-GraphQL#8]
I'm getting the following error when trying to execute a query using "Simple Example" code provided in the readme.

### Error: 
`"Unknown operation named \"\"." when executing example query`

### Query : 

    {
        getUser(id:"aaron"){
            firstName
            lastName
        }
    }

Any help would be appreciated!

**Comment by aaronwlee** [comment]
fixed! :)

**Comment by nicolaszu** [comment]
Awesome, thanks!
